name: jforsythe
favicon: null
layout_spectrum: 0.4997276917565614
typography_spectrum: 0.69259
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7e7f81'
    - '#000000'
    - '#008100'
    - '#ff4a34'
    - '#00eb00'
  brandStrength: 0.75
  lightness: 0.26839675148949027
  saturation: 0.23850756767205894
  rhythmicContrast: 0.13641218794509768
purpose: []
