name: jforsythe
favicon: null
layout_spectrum: 0.4997276917565614
typography_spectrum: 0.24624
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3bafc8'
    - '#a4fefc'
    - '#00fefc'
    - '#ffa73e'
  brandStrength: 0.75
  lightness: 0.26839675148949027
  saturation: 0.23850756767205894
  rhythmicContrast: 0.5
purpose: []
